type Query {
  getPais(filter: PaisFilter): Pais
  getPaises(sortby: [SortBy]): [Pais]
}

type Pais {
  _id: ID
  country: String
  pais: String
  casos: Int
  casosHoy: Int
  muertes: Int
  muertesHoy: Int
  recuperados: Int
  casosActivos: Int
  casosCriticos: Int
  bandera: String
  latitud: Float
  longitud: Float
}

input PaisFilter {
  _id: ID
  pais: String
}