type Query {
  getRegion(filter: RegionFilter): Region
  getRegiones(sortby: [SortBy]): [Region]
}

type Region {
  _id: ID
  region: String
  casos: Int
  muertes: Int
  recuperados: Int
  latitud: Float
  longitud: Float
}

input RegionFilter {
  _id: ID
  region: String
}